# Numpy

In [2]:
# Why we use NUMPY - Library

# 1. NumPy provides efficient storage
          #  it reduce space for the data storage
          #  commparasion  to LIST it works better, e.g. Rmax

# 2. It also provides better way of handling data for processing
        # you can use ready made functions

# 3. It is fast

# 4. it is easy to learn

# 5. NumPy uses relatively less memory to store data
        # here, you can access memory location like pointers in C


In [3]:
# pip install numpy
# intially lets import Numpy
# import numpy as np

** This**

*** This***

In [2]:
import numpy as np

myarr=np.array([3,6,32,7])  # 1-D array
print(myarr)
print(myarr.dtype)

[ 3  6 32  7]
int32


In [5]:
myarr=np.array([3,6,32,7], np.int8)  # (Specify data type) 1-D array
print(myarr)
print(myarr.dtype)

[ 3  6 32  7]
int8


In [6]:
myarr1=np.array([3,6,324446666,7], np.int8)
# myarr1 # output (-8) doest work becouase int 8 couldnot handle big numbers
print(myarr1)

[  3   6 -54   7]


In [7]:
myarr1=np.array([3,6,324446666,7], np.int32)
# myarr1 # It works because int 32 covers big range of data
print(myarr1)
print(type(myarr1))
print(myarr1.dtype)

# Memory managment is in your hand. by default it could take int 32
# you may take int 8 instead of int 32 to save memory if needed


[        3         6 324446666         7]
<class 'numpy.ndarray'>
int32


In [8]:
myarr=np.array([3,6,32,7], np.int8)
print(myarr)
print(myarr.shape)

# acces the array through index location  1 colum
myarr[1]

[ 3  6 32  7]
(4,)


6

In [9]:
myarr=np.array([[3,6,32,7]]) # Convert 1-D array to 2-D array
print(myarr.shape) # order is 1 row, 4 colum

# acces the array through index location - 0 row, 1 colum
myarr[0,1]  

(1, 4)


6

In [10]:
print(myarr)
print(myarr[0,1])

# change the value of element of array
myarr[0,1]=45 
print(myarr)
print(myarr[0,1])

[[ 3  6 32  7]]
6
[[ 3 45 32  7]]
45


In [11]:
# There are 5 general mechanism to create arrays

# 1st method: Conversion from other python structures (list, tuple)

myarr=np.array([3,6,32,7])

# 2nd method: Intrinsic numpy array creation objects(arrange, ones, zeros etc)
# 3rd method: Reading arrays from disk, either from standard or custom formats
# 4th method: Creating arrays from raw bytes through use of strings and buffers
# 5th mehtod: Use special library functions (e.g. random)


## 1st method (array creation): Conversion from other python structures (list, tuple)*

In [12]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]]) 
# 2-D array, double big brackets are used
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [13]:
listarray.dtype

dtype('int32')

In [14]:
listarray.shape

(3, 3)

In [15]:
listarray.size

9

In [16]:
set_arr = np.array({34,23,23}) # numpy through set / dictionary
#  it is dtype: object. objects are not always efficient
# generally, array will be made from int or float
print(set_arr.dtype)

object


In [17]:
## Multi Diemesional array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]
arr=np.array([my_lst1,my_lst2,my_lst3])

print(arr)
print(arr.shape)
print(arr.reshape(5,3))
print(arr.reshape(1,15)) # no of element remains same (in this case 15)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]
(3, 5)
[[1 2 3]
 [4 5 2]
 [3 4 5]
 [6 9 7]
 [6 8 9]]
[[1 2 3 4 5 2 3 4 5 6 9 7 6 8 9]]


In [18]:
## Multi Diemesional array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]
arr=np.array([my_lst1,my_lst2,my_lst3])
print(arr.dtype)
print(arr)

int32
[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


## Indexing

In [19]:
print(arr[:,:]) # All rows and all colums

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [20]:
print(arr[0:1,:])  # Start from 0th row to before 1st row - and all colums

[[1 2 3 4 5]]


In [21]:
print(arr[0:2,:]) # Start from 0th row to before 2nd row (1st two rows) - all colums
print(arr[0:3,:]) # Start from 0th row to before 3rd row (1st 03 rows) - all colums

[[1 2 3 4 5]
 [2 3 4 5 6]]
[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [23]:
print(arr[0:2,:]) # Start:0th row to before 2nd row (1st two rows) - all colums
print(arr[0:2,0:2]) # Start:0th row to before 2nd row (1st two rows) - and
# Start:0th col to before 2nd col (1st two cols) 
print(arr[1:,3:])
# Start:1st row to all rows- and 3rd col to all cols  

[[1 2 3 4 5]
 [2 3 4 5 6]]
[[1 2]
 [2 3]]
[[5 6]
 [8 9]]


## 2nd method: Intrinsic numpy array creation objects(arrange, ones, zeros etc)

In [25]:
zeros = np.zeros((5))  # 1 D, by default it is floating
zeros

array([0., 0., 0., 0., 0.])

In [26]:
zeros = np.zeros((2,5))  # 2 D
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
zeros.dtype

dtype('float64')

In [28]:
zeros.shape

(2, 5)

In [18]:
np.ones(4) # 1-D, it is by default float

array([1., 1., 1., 1.])

In [31]:
np.ones((2,5),dtype=int) # 2-D, specify int

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [39]:
arr=np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
rng = np.arange(15) # make an array of 15 numbers
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
arr=np.arange(1,10, step=2)
arr

array([1, 3, 5, 7, 9])

In [43]:
np.random.randint(0,100,8) # random integer between 0 to 100 (8 numbers)

array([96, 25, 31, 13, 52, 58,  8, 93])

In [44]:
a=np.random.randint(0,100,8).reshape(2,4)
a

array([[68, 69, 37, 48],
       [95, 59, 95, 19]])

In [53]:
# return the value between interval [0.0, 1.0]  -  Float
a=np.random.random_sample()  # output random float value
print(a)


0.8608903362431596


In [50]:
a= np.random.random_sample((5,))
print(a)
a.shape

[0.4047907  0.04701183 0.63734691 0.99350069 0.2979636 ]


(5,)

In [51]:
a=np.random.random_sample((1,3)) # Output 2D Array filled with random floats
print(a)
a.shape

[[0.14767563 0.75896362 0.18710585]]


(1, 3)

In [38]:
np.random.random_sample((1,5))
# It returns an array of specified shape and fills it with random floats 
# in the half-open interval [0.0, 1.0).

array([[0.4350403 , 0.86982456, 0.0503177 , 0.33743205, 0.22149708]])

In [54]:
a=np.random.random_sample((3, 2, 1)) 
# Output 3D Array filled with random floats
print(a)
a.shape

[[[0.64655932]
  [0.79587687]]

 [[0.35418865]
  [0.98385528]]

 [[0.11615668]
  [0.02603095]]]


(3, 2, 1)

The difference between a normal distribution and standard normal distribution is that a normal distribution can take on any value as its mean and standard deviation. On the other hand, a standard normal distribution has always the fixed mean and standard deviation.
- The standard normal distribution is a normal distribution with mean μ = 0 and standard deviation σ = 1.
- Normal distribution, also known as the Gaussian distribution, is a probability distribution that is symmetric about the mean, showing that data near the mean are more frequent in occurrence than data far from the mean.

In [31]:
np.random.rand(3,3) # uniform distribution (b/w 0 to 1) and random sampling

array([[0.36244336, 0.60523158, 0.8428384 ],
       [0.21565611, 0.42174299, 0.90755712],
       [0.09086449, 0.27491883, 0.34090612]])

In [33]:
arr_ex=np.random.randn(4,4)  # Standard Normal distribution
arr_ex

array([[-0.97440565, -0.02563261,  0.47416025, -0.4511295 ],
       [ 0.82149753, -0.99468942,  1.01362221,  1.17846688],
       [-1.16947272, -1.36811922,  0.08565563, -1.82500362],
       [-0.50411384, -0.60129408,  0.16934354, -0.71582417]])

## Copy function and boardcasting

In [56]:
# Copy function and boardcasting
arr=np.arange(1,10)
print(arr)
arr[3:]=100  # From index 3 all element will be converted to 100
arr

[1 2 3 4 5 6 7 8 9]


array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [57]:
arr1=arr
arr1[3:]=500
arr1

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [58]:
print(arr)
arr1[3:]=1000
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]


In [59]:
#  Sone conditions are very useful in  data explainatery analysis
#val=2
arr<2

array([ True, False, False, False, False, False, False, False, False])

In [60]:
print(arr)
print(arr*2)
print(arr/2)
print(arr%2)

[   1    2    3 1000 1000 1000 1000 1000 1000]
[   2    4    6 2000 2000 2000 2000 2000 2000]
[  0.5   1.    1.5 500.  500.  500.  500.  500.  500. ]
[1 0 1 0 0 0 0 0 0]


In [64]:
arr=np.arange(1,10)
print(arr)
print(arr[arr<5]) # Returns the no of values to be true
print(arr[arr>5])
print(arr[arr>=7])

[1 2 3 4 5 6 7 8 9]
[1 2 3 4]
[6 7 8 9]
[7 8 9]


In [65]:
# Equally spaced points
lspace = np.linspace(1,5,12) # give the array of 12 number equally spans from 1 to 5
lspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [66]:
lspace = np.linspace(1,4,4) 
lspace

array([1., 2., 3., 4.])

In [9]:
# Empty()
# The empty() function is used to create a new array of given shape and type,
# without initializing entries.
emp = np.empty((4,6))  # random number filling of elements of array 4*6
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.33511969e-306, 1.33508845e-306, 1.33511969e-306],
       [6.23037996e-307, 6.23053954e-307, 9.34609790e-307,
        8.45593934e-307, 9.34600963e-307, 1.86921143e-306],
       [6.23061763e-307, 8.90104239e-307, 6.89804132e-307,
        9.34605716e-307, 1.37962456e-306, 1.42418172e-306],
       [2.04712906e-306, 7.56589622e-307, 1.11258277e-307,
        8.90111708e-307, 2.11389826e-307, 1.11260619e-306]])

What is NP Empty_like?
empty_like() function in Python is used to return a new array with the same shape and data type as the one passed to it. Note: The numpy. empty_like() function does not initialize the returned array.

In [68]:
# creating a prototype or array_like objec
myarray = ([1,2,3], [4,5,6])  
print(myarray)
# using the numpy.empty() function 
newarray = np.empty_like(myarray)

print(newarray)

([1, 2, 3], [4, 5, 6])
[[   37258796  1069737737   347861477]
 [ 1072187758 -1655318144  1070068501]]


In [69]:
# Identity matrix creation
ide =np.identity(5) 
print(ide)
print(ide.shape)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)


In [70]:
ide =np.identity(45) # Identity matrix creation
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [71]:
print(ide.shape)

(45, 45)


In [72]:
arr = np.arange(45)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [73]:
arr.reshape(3,15) # here 45 numbers are divided in 3*15, other setting could 
# be done if possible the above arr is not changed. it could be changed if 
# arr = arr.reshape(3,15)
# Conversion from 1D to 2D

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]])

The numpy.ravel() functions returns contiguous flattened array(1D array with all the input-array elements and with the same type as it).

In [75]:
arr = arr.ravel()  # again convert to 1 D
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [76]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [77]:
arr.reshape(3,33) # here 99 numbers are divided in 3*33, other setting could 
# be done if possible the above arr is not changed. it could be changed if 
# arr = arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [78]:
# the above arr is not changed. it could be changed if 
arr = arr.reshape(3,33) # Conversion from 1D to 2D
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [79]:
arr = arr.ravel()  # again convert to 1 D
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [80]:
arr.shape # 1 D

(99,)

## Axis in numPy
- 1-D  -- Axis 0 -- Rows
- 2-D  -- Axis 1 -- Colums

In [5]:
x=[[1,2,3],[4,5,6],[7,1,0]]
ar=np.array(x)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [4]:
ar.sum(axis=0) # row wise addition

array([12,  8,  9])

In [5]:
ar.sum(axis=1) # column wise addition 

array([ 6, 15,  8])

In [45]:
ar.T # Transpose of array

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [8]:
# It will give the flat array in one line
ar.flat
for item in ar.flat:
    print(item) 

1
2
3
4
5
6
7
1
0


In [9]:
ar.ndim # no of dimension (2 dimensional matrix)

2

In [10]:
ar.size # no of elements

9

In [11]:
ar.nbytes # total bytes consumed

36

In [12]:
one = np.array([1,3,4,636,2]) # 1-D array
one.argmax() 
# Return the value of index where our array has maximum value 
# (in our case 3 (636), strating from 0) 
# here, used as a function as we are using brakets
# if we used with brackets these are attributes e.g (ar.size)

3

In [13]:
one.argmin() # return the index of minimum value (our case it first)

0

In [15]:
print(one)
one.argsort() 
# give the indexes of elements which reflects the increasing order elements

[  1   3   4 636   2]


array([0, 4, 1, 2, 3], dtype=int64)

In [16]:
# now 2 Dimensional array
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [17]:
ar.argmin() 
# First it will put all rows in one line and then count the index of minimum value element.
# in our case it 0 @ index 8

8

In [19]:
print(ar)
ar.argmax() # 2-D method

[[1 2 3]
 [4 5 6]
 [7 1 0]]


6

In [6]:
print(ar)
ar.argmax(axis=0)
# Frist col largest number is on index 2 (7)
# 2nd col largest number is on index 1 (5)
# 3rd col largest number is on index 1 (6)

[[1 2 3]
 [4 5 6]
 [7 1 0]]


array([2, 1, 1], dtype=int64)

In [7]:
ar.argmax(axis=1)

# Frist row largest number is on index 2 (3)
# 2nd col largest number is on index 2 (6)
# 3rd col largest number is on index 0 (7)

array([2, 2, 0], dtype=int64)

In [9]:
print(ar)
ar.argsort(axis=1)  # 1(0) 2(1) 3(2) first colum indeces
                    # 4(0) 5(1) 6(2) 2nd colum indeces
                    # 0(0) 1(1) 7(2) 3rd  -- 7(2) 1(1) 0(0) 

[[1 2 3]
 [4 5 6]
 [7 1 0]]


array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [10]:
print(ar)
ar.argsort(axis=0)

                    # 1(0) 1(2) 0(2) 
                    # 4(1) 2(0) 3(0) 
                    # 7(2) 5(1) 6(1) 

[[1 2 3]
 [4 5 6]
 [7 1 0]]


array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [11]:
print(ar)
ar.ravel() # matrix flatens # 1D

[[1 2 3]
 [4 5 6]
 [7 1 0]]


array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [12]:
ar.reshape((9,1)) # 2D

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [13]:
ar.reshape((9,)) # (9,0) 1D

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [14]:
ar2=np.array([[1,2,1],
            [4,0,6],
            [8,1,0]])

In [15]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [16]:
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [18]:
# Element by element addition of Numpy
print(ar)
print(ar2)
ar + ar2 # this work can not be done in List

[[1 2 3]
 [4 5 6]
 [7 1 0]]
[[1 2 1]
 [4 0 6]
 [8 1 0]]


array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [19]:
# If you have two list
# if we will try to add list it cannot be done, it will be extended
# Numpy allows you do matrix operation not List
[324, 34] + [34, 546]  


[324, 34, 34, 546]

In [20]:
ar * ar2 # element-wise multiplication 

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [21]:
np.sqrt(ar)  # Element-wise square root

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [22]:
ar.sum() # Sum of all elemens

29

In [23]:
ar.max() # max element value

7

In [24]:
ar.min() # min element value

0

In [26]:
print(ar)
np.where(ar>5) # return the location where ar value is greater than 5
# (1,2)= 6 & (2,0)=7

[[1 2 3]
 [4 5 6]
 [7 1 0]]


(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [27]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [78]:
type(np.where(ar>5)) # output will be saved in a tuple

tuple

In [29]:
print(ar)
np.count_nonzero(ar) # return the index of non zero elements 0 @ index 8

[[1 2 3]
 [4 5 6]
 [7 1 0]]


8

In [80]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [31]:
np.nonzero(ar) # return row*col location of non zero elements

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [32]:
ar[1,2] = 0
np.nonzero(ar) # now (1,2) will be disappear as it is now zero

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [34]:
# we already said that numpy takes less space, to show it 

import sys

py_ar = [0,4,55,2]       # normal python array
np_ar = np.array(py_ar)  # Same array in numpy format

In [35]:
sys.getsizeof(1) * len(py_ar)   # size of single element * total

112

In [36]:
np_ar.itemsize * np_ar.size    # size of single element * total

16

In [87]:
# Above shows that numpy takes very less memory space

In [ ]:
# see at google "Scipy.org" and methods and attributes